### ISSUE TITLE
Need fast way to save/reload a line (using binary data)

### ISSUE THREAD

**Issue by giadarol** [xsuite/xsuite#12]

**Comment by giadarol** [comment]
Can be used also to improve speed of Line.copy

**Comment by giadarol** [comment]
Some info for @szymonlopaciuk  in case you start working on this:

The data structure is assembled here:
https://github.com/xsuite/xtrack/blob/main/xtrack/line_frozen.py

Here the kernel is built
https://github.com/xsuite/xtrack/blob/35ac64ef34c15eb8a4636dde93a8133bb2fb85cd/xtrack/tracker.py#L575

Here some initialization happens:
https://github.com/xsuite/xtrack/blob/35ac64ef34c15eb8a4636dde93a8133bb2fb85cd/xtrack/tracker.py#L260

Here the kernel is actually called:
https://github.com/xsuite/xtrack/blob/35ac64ef34c15eb8a4636dde93a8133bb2fb85cd/xtrack/tracker.py#L1063

**Comment by szymonlopaciuk** [comment]
Since the serialisation is supposed to be fast, it makes sense to limit the number of copying between buffers to the minimum. In particular, [here](https://github.com/xsuite/xtrack/blob/main/xtrack/line_frozen.py#L33) if all the line elements are already in the same buffer, we just reuse that buffer for all the other line-related data.

My current idea for structuring the line *metadata* is something like:
```python
class LineData(xo.Struct):
    num_elements = xo.UInt64
    elements = ElementRefClass[num_elements]
    names = xo.Ref(xo.String)[num_elements]
    type_names = xo.Ref(xo.String)[num_elements]

# Elswhere in the buffer live the actual elements and strings
```

There are two issues to solve here though.

When we write the buffer containing the elements together with the above metadata to a file, all the other contents of the buffer will also end up in that file. This will not corrupt the data, but can lead to bigger-than-necessary files if we're not careful. The way to avoid this is to copy only the things we need into a fresh buffer when serialising to a file, but not neccesarily when we just want to pass the metadata to the C code.

The other issue if we were to decide to go with the no-copying route (i.e., just writing the whole buffer to disk, whatever is inside) is that we then have no idea when `LineData` actually is. One solution would be to place a pointer to `LineData` at the end of the buffer, so that we can find it, and then decode everything else.

I think the best way would be to copy the data afresh into a new buffer if we need it to be deserialisable. What are your thoughts?

**Comment by szymonlopaciuk** [comment]
I had a chat with @rdemaria that cleared up a few things, seems that he agrees that putting `LineData` at the beginning of the buffer for serialisation is the right way. Also, now knowing a bit better how arrays work in xobject I think the metadata can be simplified:
```python
class LineData(xo.Struct):
    num_elements = xo.UInt64
    types_names_for_union_ref = xo.String[num_kinds_of_elements]
    elements = ElementRefClass[num_elements]
    names = xo.String[num_elements]
    type_names = xo.Ref(xo.String)[num_elements]
```

**Comment by giadarol** [comment]
Perfect for me
